Добавление кэша #9
nikitaKunevich/Async_API_sprint_3 pull request #13
Opened 2021-02-10 18:17 UTC by meshchaninov

Добавление кэша

2021-02-10 20:09 UTC, nikitaKunevich requested changes
Отлично! Есть небольшое замечание, легко исправишь

2021-02-10 20:09 UTC, nikitaKunevich commented on src/models/film.py
> +class Films(BaseModel):
Расскажи: а в чем преимущество того, что мы создали модель для фильмов?
В том, что будет использоваться orjson?
Но я нигде не увидел, где используется сериализация/десериализация модели Films в json.
А Структура стала сложнее.
"flat is better than nested" из Zen of Python:)

2021-02-10 20:09 UTC, nikitaKunevich commented on src/db/cache.py
> +    async def __setitem__(self, key: str, value: Any) -> None:
Возможно ошибка, можно лучше: `__setitem__` и `__getitem__` не используются в коде. И `__setitem__` не может быть корутиной.

2021-02-11 06:37 UTC, meshchaninov commented on src/db/cache.py
> +    async def __setitem__(self, key: str, value: Any) -> None:
Почему не может быть?

2021-02-11 06:37 UTC, meshchaninov commented on src/models/film.py
> +class Films(BaseModel):
Используется:
```
async def get_by_elastic_query(self, query_elastic: dict) -> Optional[Films]:
        key = f'query:{str(query_elastic)}'
        data = await self.get(key)
        if not data:
            return None
        return Films.parse_raw(data)
```
Это единственный очевидный способ стерилизовать пачку https://stackoverflow.com/questions/58068001/python-pydantic-using-a-list-with-json-objects

2021-02-11 17:50 UTC, nikitaKunevich reviewed
Момент с __set/getitem__ посмотри

2021-02-11 17:50 UTC, nikitaKunevich commented on src/db/cache.py
> +    async def __setitem__(self, key: str, value: Any) -> None:
Как ты напишешь await cache[key] = value
Чтобы не вызвать Exception?

2021-02-11 17:50 UTC, nikitaKunevich commented on src/models/film.py
> +class Films(BaseModel):
pydantic мощная библиотека, и может парсить стандартные коллекции:
https://github.com/samuelcolvin/pydantic/issues/1789

2021-02-11 17:50 UTC, nikitaKunevich commented on src/models/film.py
> +class Films(BaseModel):
Но это опционально, можешь не менять, так просто меньше сущностей

2021-02-11 17:50 UTC, nikitaKunevich commented on src/db/cache.py
> +    async def __setitem__(self, key: str, value: Any) -> None:
Ну и вообще лучше убери оба метода, т.к. ты их нигде не используешь

2021-02-13 09:02 UTC, InnokentyDM approved these changes

2021-02-13 11:26 UTC, merged